interaction:
  - name: "Ffruitsequences_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.ffruitsequences.Ffruitsequences_interaction.FfruitsequencesInteraction"
    config: {}
