interaction:
  - name: "Ckamalolmolkspainting_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.graphical_puzzles.ckamalolmolkspainting.Ckamalolmolkspainting_interaction.CkamalolmolkspaintingInteraction"
    config: {}
