instruction_generators:
  config_1:
    config:
      max_words: 14
      min_words: 4
      mode: solvable
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/logical_reasoning/cbeautifullyrics/configs/Cbeautifullyrics_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/logical_reasoning/cbeautifullyrics/configs/Cbeautifullyrics_interaction_config.yaml
    generation_ratio: 0.25
  config_2:
    config:
      max_words: 7
      min_words: 4
      mode: unsolvable
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/logical_reasoning/cbeautifullyrics/configs/Cbeautifullyrics_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/logical_reasoning/cbeautifullyrics/configs/Cbeautifullyrics_interaction_config.yaml
    generation_ratio: 0.25
  config_3:
    config:
      max_words: 8
      min_words: 5
      mode: solvable
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/logical_reasoning/cbeautifullyrics/configs/Cbeautifullyrics_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/logical_reasoning/cbeautifullyrics/configs/Cbeautifullyrics_interaction_config.yaml
    generation_ratio: 0.25
  config_4:
    config:
      max_words: 10
      min_words: 5
      mode: unsolvable
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/logical_reasoning/cbeautifullyrics/configs/Cbeautifullyrics_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/logical_reasoning/cbeautifullyrics/configs/Cbeautifullyrics_interaction_config.yaml
    generation_ratio: 0.25

# 全局配置
global_config:
  # 指令生成器类的完整路径
  class_name: "internbootcamp.bootcamps.bootcamps_v1.logical_reasoning.cbeautifullyrics.Cbeautifullyrics_instruction_generator.CbeautifullyricsInstructionGenerator"
  
  # 随机种子配置
  enable_random_seed: true
  default_seed: 999
  
  # 数据集划分配置
  default_split_samples:
    train: 1000
    test: 100
  
  # 是否启用数据打乱
  shuffle: true

  # 是否生成parquet文件
  gen_parquet: false
