interaction:
  - name: "Cmaximandmatrix_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.cmaximandmatrix.Cmaximandmatrix_interaction.CmaximandmatrixInteraction"
    config: {}
