interaction:
  - name: "Cdividingthenumbers_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.cdividingthenumbers.Cdividingthenumbers_interaction.CdividingthenumbersInteraction"
    config: {}
