instruction_generators:
  config_1:
    config:
      size: [8, 8]
      expect_camp_number: 6
      random_rate: 0.3
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/campsite/configs/campsite_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/campsite/configs/campsite_interaction_config.yaml
    generation_ratio: 0.20
  config_2:
    config:
      size: [6, 4]
      expect_camp_number: 3
      random_rate: 0.2
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/campsite/configs/campsite_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/campsite/configs/campsite_interaction_config.yaml
    generation_ratio: 0.20
  config_3:
    config:
      size: [7, 7]
      expect_camp_number: 5
      random_rate: 0.25
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/campsite/configs/campsite_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/campsite/configs/campsite_interaction_config.yaml
    generation_ratio: 0.20
  config_4:
    config:
      size: [4, 4]
      expect_camp_number: 2
      random_rate: 0.1
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/campsite/configs/campsite_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/campsite/configs/campsite_interaction_config.yaml
    generation_ratio: 0.20
  config_5:
    config:
      size: [6, 6]
      expect_camp_number: 4
      random_rate: 0.2
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/campsite/configs/campsite_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/campsite/configs/campsite_interaction_config.yaml
    generation_ratio: 0.20

# 全局配置
global_config:
  # 指令生成器类的完整路径
  class_name: "internbootcamp.bootcamps.bootcamps_v1.graphical_puzzles.campsite.campsite_instruction_generator.CampsiteInstructionGenerator"
  
  # 随机种子配置
  enable_random_seed: true
  default_seed: 999
  
  # 数据集划分配置
  default_split_samples:
    train: 1000
    test: 100
  
  # 是否启用数据打乱
  shuffle: true

  # 是否生成parquet文件
  gen_parquet: false
