interaction:
  - name: "Canagramsearch_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.canagramsearch.Canagramsearch_interaction.CanagramsearchInteraction"
    config: {}
