interaction:
  - name: "Earpaandagamewithmojtaba_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.earpaandagamewithmojtaba.Earpaandagamewithmojtaba_interaction.EarpaandagamewithmojtabaInteraction"
    config: {}
