interaction:
  - name: "Cacookieforyou_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.logical_reasoning.cacookieforyou.Cacookieforyou_interaction.CacookieforyouInteraction"
    config: {}
