interaction:
  - name: "Comnomandcandies_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.comnomandcandies.Comnomandcandies_interaction.ComnomandcandiesInteraction"
    config: {}
