interaction:
  - name: "Dgamewithpowers_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.logical_reasoning.dgamewithpowers.Dgamewithpowers_interaction.DgamewithpowersInteraction"
    config: {}
