interaction:
  - name: "Cacolourfulprospect_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.mathematical_modeling.cacolourfulprospect.Cacolourfulprospect_interaction.CacolourfulprospectInteraction"
    config: {}
