instruction_generators:
  config_1:
    config:
      m: 100
      l: 100
      r: 1000
      k: 3
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/eanniversary/configs/Eanniversary_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/eanniversary/configs/Eanniversary_interaction_config.yaml
    generation_ratio: 0.25
  config_2:
    config:
      m: 10
      l: 1
      r: 8
      k: 2
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/eanniversary/configs/Eanniversary_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/eanniversary/configs/Eanniversary_interaction_config.yaml
    generation_ratio: 0.25
  config_3:
    config:
      m: 1000000000
      l: 1000000000
      r: 1000000000000
      k: 1000000
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/eanniversary/configs/Eanniversary_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/eanniversary/configs/Eanniversary_interaction_config.yaml
    generation_ratio: 0.25
  config_4:
    config:
      m: 1000000
      l: 1000000
      r: 10000000
      k: 10000
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/eanniversary/configs/Eanniversary_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/eanniversary/configs/Eanniversary_interaction_config.yaml
    generation_ratio: 0.25

# 全局配置
global_config:
  # 指令生成器类的完整路径
  class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.eanniversary.Eanniversary_instruction_generator.EanniversaryInstructionGenerator"
  
  # 随机种子配置
  enable_random_seed: true
  default_seed: 999
  
  # 数据集划分配置
  default_split_samples:
    train: 1000
    test: 100
  
  # 是否启用数据打乱
  shuffle: true

  # 是否生成parquet文件
  gen_parquet: false
