interaction:
  - name: "E2twilightandancientscrollharderversion_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.e2twilightandancientscrollharderversion.E2twilightandancientscrollharderversion_interaction.E2twilightandancientscrollharderversionInteraction"
    config: {}
