interaction:
  - name: "Cwateringflowers_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.mathematical_modeling.cwateringflowers.Cwateringflowers_interaction.CwateringflowersInteraction"
    config: {}
