interaction:
  - name: "Csantaclausandrobot_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.csantaclausandrobot.Csantaclausandrobot_interaction.CsantaclausandrobotInteraction"
    config: {}
