interaction:
  - name: "Cworldeaterbrothers_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.graphical_puzzles.cworldeaterbrothers.Cworldeaterbrothers_interaction.CworldeaterbrothersInteraction"
    config: {}
