interaction:
  - name: "Dnashmatrix_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.graphical_puzzles.dnashmatrix.Dnashmatrix_interaction.DnashmatrixInteraction"
    config: {}
