interaction:
  - name: "Ctrailinglovesorloeufs_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.mathematical_modeling.ctrailinglovesorloeufs.Ctrailinglovesorloeufs_interaction.CtrailinglovesorloeufsInteraction"
    config: {}
