interaction:
  - name: "Dsashaandonemorename_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.character_puzzles.dsashaandonemorename.Dsashaandonemorename_interaction.DsashaandonemorenameInteraction"
    config: {}
