interaction:
  - name: "Cpredictoutcomeofthegame_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.mathematical_modeling.cpredictoutcomeofthegame.Cpredictoutcomeofthegame_interaction.CpredictoutcomeofthegameInteraction"
    config: {}
