interaction:
  - name: "Cconstanzesmachine_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.cconstanzesmachine.Cconstanzesmachine_interaction.CconstanzesmachineInteraction"
    config: {}
