instruction_generators:
  config_1:
    config:
      A: 10
      B: 5
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ctavasandkarafs/configs/Ctavasandkarafs_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ctavasandkarafs/configs/Ctavasandkarafs_interaction_config.yaml
    generation_ratio: 0.14
  config_2:
    config:
      A: 5
      B: 2
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ctavasandkarafs/configs/Ctavasandkarafs_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ctavasandkarafs/configs/Ctavasandkarafs_interaction_config.yaml
    generation_ratio: 0.14
  config_3:
    config:
      A: 1
      B: 100
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ctavasandkarafs/configs/Ctavasandkarafs_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ctavasandkarafs/configs/Ctavasandkarafs_interaction_config.yaml
    generation_ratio: 0.14
  config_4:
    config:
      A: 10
      B: 10
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ctavasandkarafs/configs/Ctavasandkarafs_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ctavasandkarafs/configs/Ctavasandkarafs_interaction_config.yaml
    generation_ratio: 0.14
  config_5:
    config:
      A: 2
      B: 3
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ctavasandkarafs/configs/Ctavasandkarafs_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ctavasandkarafs/configs/Ctavasandkarafs_interaction_config.yaml
    generation_ratio: 0.14
  config_6:
    config:
      A: 1
      B: 1
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ctavasandkarafs/configs/Ctavasandkarafs_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ctavasandkarafs/configs/Ctavasandkarafs_interaction_config.yaml
    generation_ratio: 0.14
  config_7:
    config:
      A: 100
      B: 100
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ctavasandkarafs/configs/Ctavasandkarafs_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ctavasandkarafs/configs/Ctavasandkarafs_interaction_config.yaml
    generation_ratio: 0.14

# 全局配置
global_config:
  # 指令生成器类的完整路径
  class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.ctavasandkarafs.Ctavasandkarafs_instruction_generator.CtavasandkarafsInstructionGenerator"
  
  # 随机种子配置
  enable_random_seed: true
  default_seed: 999
  
  # 数据集划分配置
  default_split_samples:
    train: 1000
    test: 100
  
  # 是否启用数据打乱
  shuffle: true

  # 是否生成parquet文件
  gen_parquet: false
