instruction_generators:
  config_1:
    config:
      max_n: 50
      min_weight: 1
      max_weight: 1000000
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ccleverfatrat/configs/Ccleverfatrat_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ccleverfatrat/configs/Ccleverfatrat_interaction_config.yaml
    generation_ratio: 0.17
  config_2:
    config:
      max_n: 40
      min_weight: 10000
      max_weight: 100000
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ccleverfatrat/configs/Ccleverfatrat_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ccleverfatrat/configs/Ccleverfatrat_interaction_config.yaml
    generation_ratio: 0.17
  config_3:
    config:
      max_n: 30
      min_weight: 500
      max_weight: 5000
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ccleverfatrat/configs/Ccleverfatrat_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ccleverfatrat/configs/Ccleverfatrat_interaction_config.yaml
    generation_ratio: 0.17
  config_4:
    config:
      max_n: 20
      min_weight: 1000
      max_weight: 10000
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ccleverfatrat/configs/Ccleverfatrat_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ccleverfatrat/configs/Ccleverfatrat_interaction_config.yaml
    generation_ratio: 0.17
  config_5:
    config:
      max_n: 15
      min_weight: 200
      max_weight: 2000
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ccleverfatrat/configs/Ccleverfatrat_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ccleverfatrat/configs/Ccleverfatrat_interaction_config.yaml
    generation_ratio: 0.17
  config_6:
    config:
      max_n: 1
      min_weight: 1
      max_weight: 1
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ccleverfatrat/configs/Ccleverfatrat_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/ccleverfatrat/configs/Ccleverfatrat_interaction_config.yaml
    generation_ratio: 0.17

# 全局配置
global_config:
  # 指令生成器类的完整路径
  class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.ccleverfatrat.Ccleverfatrat_instruction_generator.CcleverfatratInstructionGenerator"
  
  # 随机种子配置
  enable_random_seed: true
  default_seed: 999
  
  # 数据集划分配置
  default_split_samples:
    train: 1000
    test: 100
  
  # 是否启用数据打乱
  shuffle: true

  # 是否生成parquet文件
  gen_parquet: false
