interaction:
  - name: "Epetyaandspiders_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.epetyaandspiders.Epetyaandspiders_interaction.EpetyaandspidersInteraction"
    config: {}
