instruction_generators:
  config_1:
    config:
      a_min: 1
      a_max: 10000
      b_max: 100000
      k_max: 50
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cprimesoninterval/configs/Cprimesoninterval_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cprimesoninterval/configs/Cprimesoninterval_interaction_config.yaml
    generation_ratio: 0.25
  config_2:
    config:
      a_min: 2
      a_max: 1000000
      b_max: 1000000
      k_max: 1000000
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cprimesoninterval/configs/Cprimesoninterval_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cprimesoninterval/configs/Cprimesoninterval_interaction_config.yaml
    generation_ratio: 0.25
  config_3:
    config:
      a_min: 1
      a_max: 100
      b_max: 1000
      k_max: 10
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cprimesoninterval/configs/Cprimesoninterval_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cprimesoninterval/configs/Cprimesoninterval_interaction_config.yaml
    generation_ratio: 0.25
  config_4:
    config:
      a_min: 1
      a_max: 10
      b_max: 100
      k_max: 5
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cprimesoninterval/configs/Cprimesoninterval_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cprimesoninterval/configs/Cprimesoninterval_interaction_config.yaml
    generation_ratio: 0.25

# 全局配置
global_config:
  # 指令生成器类的完整路径
  class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.cprimesoninterval.Cprimesoninterval_instruction_generator.CprimesonintervalInstructionGenerator"
  
  # 随机种子配置
  enable_random_seed: true
  default_seed: 999
  
  # 数据集划分配置
  default_split_samples:
    train: 1000
    test: 100
  
  # 是否启用数据打乱
  shuffle: true

  # 是否生成parquet文件
  gen_parquet: false
