interaction:
  - name: "Cprimesoninterval_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.cprimesoninterval.Cprimesoninterval_interaction.CprimesonintervalInteraction"
    config: {}
