interaction:
  - name: "Dchallengesinschool41_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.logical_reasoning.dchallengesinschool41.Dchallengesinschool41_interaction.Dchallengesinschool41Interaction"
    config: {}
