interaction:
  - name: "D2rpdandrapsheethardversion_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.cryptography.d2rpdandrapsheethardversion.D2rpdandrapsheethardversion_interaction.D2rpdandrapsheethardversionInteraction"
    config: {}
