interaction:
  - name: "Cdashaandpassword_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.cdashaandpassword.Cdashaandpassword_interaction.CdashaandpasswordInteraction"
    config: {}
