interaction:
  - name: "Aalmostarithmeticalprogression_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.aalmostarithmeticalprogression.Aalmostarithmeticalprogression_interaction.AalmostarithmeticalprogressionInteraction"
    config: {}
