interaction:
  - name: "Cfoolsandroads_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.cfoolsandroads.Cfoolsandroads_interaction.CfoolsandroadsInteraction"
    config: {}
