interaction:
  - name: "korPuzzleWordBrainTeasers_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.language_analysis.korpuzzlewordbrainteasers.korPuzzleWordBrainTeasers_interaction.KorpuzzlewordbrainteasersInteraction"
    config: {}
