interaction:
  - name: "Ewaterbalance_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.ewaterbalance.Ewaterbalance_interaction.EwaterbalanceInteraction"
    config: {}
