interaction:
  - name: "Cremovingcolumns_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.cremovingcolumns.Cremovingcolumns_interaction.CremovingcolumnsInteraction"
    config: {}
