interaction:
  - name: "Dgeneratingsets_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.mathematical_modeling.dgeneratingsets.Dgeneratingsets_interaction.DgeneratingsetsInteraction"
    config: {}
