interaction:
  - name: "Cpinkiepieeatspattycakes_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.cpinkiepieeatspattycakes.Cpinkiepieeatspattycakes_interaction.CpinkiepieeatspattycakesInteraction"
    config: {}
