interaction:
  - name: "D1kirkandabinarystringeasyversion_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.d1kirkandabinarystringeasyversion.D1kirkandabinarystringeasyversion_interaction.D1kirkandabinarystringeasyversionInteraction"
    config: {}
