instruction_generators:
  config_1:
    config:
      A: [100, 100, 100]
      v: [0, 1, 0]
      R: 20
      min_mines: 2
      max_mines: 5
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/mathematical_modeling/dspacemines/configs/Dspacemines_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/mathematical_modeling/dspacemines/configs/Dspacemines_interaction_config.yaml
    generation_ratio: 0.25
  config_2:
    config:
      A: [100, 0, 0]
      v: [0, 1, 1]
      R: 18
      min_mines: 1
      max_mines: 3
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/mathematical_modeling/dspacemines/configs/Dspacemines_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/mathematical_modeling/dspacemines/configs/Dspacemines_interaction_config.yaml
    generation_ratio: 0.25
  config_3:
    config:
      A: [0, 100, 0]
      v: [1, 1, 0]
      R: 15
      min_mines: 3
      max_mines: 5
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/mathematical_modeling/dspacemines/configs/Dspacemines_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/mathematical_modeling/dspacemines/configs/Dspacemines_interaction_config.yaml
    generation_ratio: 0.25
  config_4:
    config:
      A: [0, 0, 0]
      v: [1, 0, 0]
      R: 5
      min_mines: 1
      max_mines: 3
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/mathematical_modeling/dspacemines/configs/Dspacemines_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/mathematical_modeling/dspacemines/configs/Dspacemines_interaction_config.yaml
    generation_ratio: 0.25

# 全局配置
global_config:
  # 指令生成器类的完整路径
  class_name: "internbootcamp.bootcamps.bootcamps_v1.mathematical_modeling.dspacemines.Dspacemines_instruction_generator.DspaceminesInstructionGenerator"
  
  # 随机种子配置
  enable_random_seed: true
  default_seed: 999
  
  # 数据集划分配置
  default_split_samples:
    train: 1000
    test: 100
  
  # 是否启用数据打乱
  shuffle: true

  # 是否生成parquet文件
  gen_parquet: false
