interaction:
  - name: "Enumbertransformationii_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.enumbertransformationii.Enumbertransformationii_interaction.EnumbertransformationiiInteraction"
    config: {}
