interaction:
  - name: "Dteamsformation_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.dteamsformation.Dteamsformation_interaction.DteamsformationInteraction"
    config: {}
