interaction:
  - name: "BloodTestJudgement_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.real_world_problem.bloodtestjudgement.BloodTestJudgement_interaction.BloodtestjudgementInteraction"
    config: {}
