interaction:
  - name: "Fkonradandcompanyevaluation_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.fkonradandcompanyevaluation.Fkonradandcompanyevaluation_interaction.FkonradandcompanyevaluationInteraction"
    config: {}
