instruction_generators:
  basic:
    config:
      init_obs: 15
      joint_angles: [-2.96, 2.96]

    # 外部工具配置文件路径
    tool_config_path: "internbootcamp/bootcamps/bot_bootcamp/configs/bot_tool_config.yaml"
    interaction_config_path: "internbootcamp/bootcamps/bot_bootcamp/configs/bot_interaction_config.yaml"
    generation_ratio: 1.0

# --- 全局系统配置 ---
global_config:
  class_name: "internbootcamp.bootcamps.bot_bootcamp.bot_instruction_generator.BotInstructionGenerator"
  enable_random_seed: true
  default_seed: 42
  default_split_samples:
    train: 100
    test: 20
  shuffle: true
  gen_parquet: true
