interaction:
  - name: "bbehobjectproperties_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.logical_reasoning.bbehobjectproperties.bbehobjectproperties_interaction.BbehobjectpropertiesInteraction"
    config: {}
