instruction_generators:
  config_1:
    config:
      size: 9
      mine_ratio: 0.2
      min_hints: 6
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/korpuzzleminesweeper/configs/korPuzzleMinesweeper_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/korpuzzleminesweeper/configs/korPuzzleMinesweeper_interaction_config.yaml
    generation_ratio: 0.17
  config_2:
    config:
      size: 7
      mine_ratio: 0.25
      min_hints: 6
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/korpuzzleminesweeper/configs/korPuzzleMinesweeper_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/korpuzzleminesweeper/configs/korPuzzleMinesweeper_interaction_config.yaml
    generation_ratio: 0.17
  config_3:
    config:
      size: 9
      mine_ratio: 0.15
      min_hints: 5
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/korpuzzleminesweeper/configs/korPuzzleMinesweeper_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/korpuzzleminesweeper/configs/korPuzzleMinesweeper_interaction_config.yaml
    generation_ratio: 0.17
  config_4:
    config:
      size: 5
      mine_ratio: 0.25
      min_hints: 5
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/korpuzzleminesweeper/configs/korPuzzleMinesweeper_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/korpuzzleminesweeper/configs/korPuzzleMinesweeper_interaction_config.yaml
    generation_ratio: 0.17
  config_5:
    config:
      size: 9
      mine_ratio: 0.25
      min_hints: 7
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/korpuzzleminesweeper/configs/korPuzzleMinesweeper_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/korpuzzleminesweeper/configs/korPuzzleMinesweeper_interaction_config.yaml
    generation_ratio: 0.17
  config_6:
    config:
      size: 7
      mine_ratio: 0.15
      min_hints: 4
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/korpuzzleminesweeper/configs/korPuzzleMinesweeper_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/graphical_puzzles/korpuzzleminesweeper/configs/korPuzzleMinesweeper_interaction_config.yaml
    generation_ratio: 0.17

# 全局配置
global_config:
  # 指令生成器类的完整路径
  class_name: "internbootcamp.bootcamps.bootcamps_v1.graphical_puzzles.korpuzzleminesweeper.korPuzzleMinesweeper_instruction_generator.KorpuzzleminesweeperInstructionGenerator"
  
  # 随机种子配置
  enable_random_seed: true
  default_seed: 999
  
  # 数据集划分配置
  default_split_samples:
    train: 1000
    test: 100
  
  # 是否启用数据打乱
  shuffle: true

  # 是否生成parquet文件
  gen_parquet: false
