interaction:
  - name: "Ejeremybearimy_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.ejeremybearimy.Ejeremybearimy_interaction.EjeremybearimyInteraction"
    config: {}
