interaction:
  - name: "Dfafaandancientalphabet_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.logical_reasoning.dfafaandancientalphabet.Dfafaandancientalphabet_interaction.DfafaandancientalphabetInteraction"
    config: {}
