# Example Instruction Manager 配置
# 支持多组配置和不同的生成比例

instruction_generators:
  basic:
    config:
      B1_min: 16
      B1_max: 380
      thickness_min: 5
      thickness_max: 45
      pressure_min: 1
      pressure_max: 100
    tool_config_path: "internbootcamp/bootcamps/flangeplane_bootcamp/configs/flangeplane_tool_config.yaml"
    interaction_config_path: "internbootcamp/bootcamps/flangeplane_bootcamp/configs/flangeplane_interaction_config.yaml"
    generation_ratio: 1  

# 全局配置
global_config:
# 指令管理器类的完整相对路径
  class_name: "internbootcamp.bootcamps.flangeplane_bootcamp.flangeplane_instruction_generator.FlangeplaneInstructionGenerator"
  
  # 是否启用随机种子
  enable_random_seed: true
  
  # 默认种子值
  default_seed: 999
  
  # 默认数据集划分和样本数
  default_split_samples:
    train: 10000
    test: 100
  
  # 是否启用数据打乱
  shuffle: true

  # 是否生成parquet文件
  # gen_parquet: true