tools:
  - class_name: "internbootcamp.bootcamps.flangeplane_bootcamp.flangeplane_tools.CaeAnalysis"
    config: 
      type: "native"
    tool_schema:
      type: "function"
      function:
        name: "cae_analysis"
        description: "该工具可在“外圆柱面完全固定、内径均匀加压”的工况下，对给定参数下的平板法兰进行简化有限元应力分析。分析假设如下：材料为各向同性线弹性；变形满足小变形假设；载荷为静载；次要载荷忽略不计。计算完成后，返回法兰受力后的最大节点位移值（单位：μm）"
        parameters:
          type: "object"
          properties:
            D:
              type: "number"
              description: "外圆半径，单位为mm"
            B1:
              type: "number"
              description: "内圆半径，单位为mm"
            L:
              type: "number"
              description: "螺栓孔半径，单位为mm"
            BoltCenterRadius:
              type: "number"
              description: "螺栓孔中心所在圆的半径，单位为mm"
            thickness:
              type: "number"
              description: "厚度，单位为mm"
            bolt_count_edit:
              type: "number"
              description: "螺栓孔数目"
            Name:
              type: "string"
              description: "平板法兰的材料名称"
            YoungsModulus:
              type: "number"
              description: "平板法兰材料的杨氏模量（弹性变形刚度），单位为MPa"
            PoissonRatio:
              type: "number"
              description: "平板法兰材料的泊松比（横向收缩比例）"
            Density:
              type: "number"
              description: "平板法兰材料的密度，单位为kg/m^3"
            pressure:
              type: "number"
              description: "向平板法兰内径施加的压强，单位为MPa"
          required: ["D", "B1", "L", "BoltCenterRadius", "thickness", "bolt_count_edit", "Name", "YoungsModulus", "PoissonRatio", "Density", "pressure"]
  - class_name: "internbootcamp.bootcamps.flangeplane_bootcamp.flangeplane_tools.CostCal"
    config: 
      type: "native"
    tool_schema:
      type: "function"
      function:
        name: "cost_cal"
        description: "该工具可根据平板法兰的几何参数和材料属性，计算耗材成本（单位：¥）"
        parameters:
          type: "object"
          properties:
            D:
              type: "number"
              description: "外圆半径，单位为mm"
            B1:
              type: "number"
              description: "内圆半径，单位为mm"
            L:
              type: "number"
              description: "螺栓孔半径，单位为mm"
            thickness:
              type: "number"
              description: "厚度，单位为mm"
            bolt_count_edit:
              type: "number"
              description: "螺栓孔数目"
            Density:
              type: "number"
              description: "平板法兰材料的密度，单位为kg/m^3"
            price:
              type: "number"
              description: "材料单价，单位为¥/kg"
          required: ["D", "B1", "L", "thickness", "bolt_count_edit", "Density", "price"]
