interaction:
  - name: "Cnastiaandahiddenpermutation_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.cnastiaandahiddenpermutation.Cnastiaandahiddenpermutation_interaction.CnastiaandahiddenpermutationInteraction"
    config: {}
