instruction_generators:
  config_1:
    config:
      standard_alphabet: ABCDEFGHIJKLMNOPQRSTUVWXYZ
      reversed_alphabet: ZYXWVUTSRQPONMLKJIHGFEDCBA
      substitution_alphabet: RFDJUHABCEGIKLMNOPQSTVWXYZ
      min_length: 5
      max_length: 10
      encrypt_probability: 0.7
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/cryptography/korciphercustominverseshiftsubstitutioncipher/configs/korCipherCustomInverseShiftSubstitutionCipher_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/cryptography/korciphercustominverseshiftsubstitutioncipher/configs/korCipherCustomInverseShiftSubstitutionCipher_interaction_config.yaml
    generation_ratio: 0.50
  config_2:
    config:
      standard_alphabet: ABCDEFGHIJKLMNOPQRSTUVWXYZ
      reversed_alphabet: ZYXWVUTSRQPONMLKJIHGFEDCBA
      substitution_alphabet: RFDJUHABCEGIKLMNOPQSTVWXYZ
      min_length: 4
      max_length: 6
      encrypt_probability: 0.3
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/cryptography/korciphercustominverseshiftsubstitutioncipher/configs/korCipherCustomInverseShiftSubstitutionCipher_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/cryptography/korciphercustominverseshiftsubstitutioncipher/configs/korCipherCustomInverseShiftSubstitutionCipher_interaction_config.yaml
    generation_ratio: 0.50

# 全局配置
global_config:
  # 指令生成器类的完整路径
  class_name: "internbootcamp.bootcamps.bootcamps_v1.cryptography.korciphercustominverseshiftsubstitutioncipher.korCipherCustomInverseShiftSubstitutionCipher_instruction_generator.KorciphercustominverseshiftsubstitutioncipherInstructionGenerator"
  
  # 随机种子配置
  enable_random_seed: true
  default_seed: 999
  
  # 数据集划分配置
  default_split_samples:
    train: 1000
    test: 100
  
  # 是否启用数据打乱
  shuffle: true

  # 是否生成parquet文件
  gen_parquet: false
