interaction:
  - name: "Cconvenientforeverybody_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.mathematical_modeling.cconvenientforeverybody.Cconvenientforeverybody_interaction.CconvenientforeverybodyInteraction"
    config: {}
