interaction:
  - name: "Btheworldisjustaprogrammingtaskhardversion_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.btheworldisjustaprogrammingtaskhardversion.Btheworldisjustaprogrammingtaskhardversion_interaction.BtheworldisjustaprogrammingtaskhardversionInteraction"
    config: {}
