interaction:
  - name: "Epropagatingtree_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.epropagatingtree.Epropagatingtree_interaction.EpropagatingtreeInteraction"
    config: {}
