interaction:
  - name: "Cstablegroups_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.cstablegroups.Cstablegroups_interaction.CstablegroupsInteraction"
    config: {}
