interaction:
  - name: "Faupontrouge_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.character_puzzles.faupontrouge.Faupontrouge_interaction.FaupontrougeInteraction"
    config: {}
