instruction_generators:
  config_1:
    config:
      max_voters: 30
      max_bribe: 500
      max_candidates: 3
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/celections/configs/Celections_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/celections/configs/Celections_interaction_config.yaml
    generation_ratio: 0.14
  config_2:
    config:
      max_voters: 40
      max_bribe: 700
      max_candidates: 4
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/celections/configs/Celections_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/celections/configs/Celections_interaction_config.yaml
    generation_ratio: 0.14
  config_3:
    config:
      max_voters: 25
      max_bribe: 150
      max_candidates: 3
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/celections/configs/Celections_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/celections/configs/Celections_interaction_config.yaml
    generation_ratio: 0.14
  config_4:
    config:
      max_voters: 35
      max_bribe: 800
      max_candidates: 5
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/celections/configs/Celections_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/celections/configs/Celections_interaction_config.yaml
    generation_ratio: 0.14
  config_5:
    config:
      max_voters: 30
      max_bribe: 600
      max_candidates: 2
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/celections/configs/Celections_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/celections/configs/Celections_interaction_config.yaml
    generation_ratio: 0.14
  config_6:
    config:
      max_voters: 10
      max_bribe: 50
      max_candidates: 2
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/celections/configs/Celections_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/celections/configs/Celections_interaction_config.yaml
    generation_ratio: 0.14
  config_7:
    config:
      max_voters: 45
      max_bribe: 900
      max_candidates: 4
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/celections/configs/Celections_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/celections/configs/Celections_interaction_config.yaml
    generation_ratio: 0.14

# 全局配置
global_config:
  # 指令生成器类的完整路径
  class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.celections.Celections_instruction_generator.CelectionsInstructionGenerator"
  
  # 随机种子配置
  enable_random_seed: true
  default_seed: 999
  
  # 数据集划分配置
  default_split_samples:
    train: 1000
    test: 100
  
  # 是否启用数据打乱
  shuffle: true

  # 是否生成parquet文件
  gen_parquet: false
