interaction:
  - name: "Eluckypermutation_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.eluckypermutation.Eluckypermutation_interaction.EluckypermutationInteraction"
    config: {}
