interaction:
  - name: "Esergeyandsubway_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.esergeyandsubway.Esergeyandsubway_interaction.EsergeyandsubwayInteraction"
    config: {}
