interaction:
  - name: "Ejeffandbrackets_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.ejeffandbrackets.Ejeffandbrackets_interaction.EjeffandbracketsInteraction"
    config: {}
