interaction:
  - name: "Bandreyandproblem_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.bandreyandproblem.Bandreyandproblem_interaction.BandreyandproblemInteraction"
    config: {}
