interaction:
  - name: "Cfadiandlcm_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.mathematical_modeling.cfadiandlcm.Cfadiandlcm_interaction.CfadiandlcmInteraction"
    config: {}
