interaction:
  - name: "Ftokitsukazeandstrangerectangle_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.graphical_puzzles.ftokitsukazeandstrangerectangle.Ftokitsukazeandstrangerectangle_interaction.FtokitsukazeandstrangerectangleInteraction"
    config: {}
