interaction:
  - name: "Cannasvyatoslavandmaps_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.cannasvyatoslavandmaps.Cannasvyatoslavandmaps_interaction.CannasvyatoslavandmapsInteraction"
    config: {}
