instruction_generators:
  config_1:
    config:
      min_u: 0
      max_u: 1000
      min_v: 0
      max_v: 1000
      case_type: easy
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/dehabthexorcist/configs/Dehabthexorcist_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/dehabthexorcist/configs/Dehabthexorcist_interaction_config.yaml
    generation_ratio: 0.25
  config_2:
    config:
      min_u: 0
      max_u: 0
      min_v: 0
      max_v: 0
      case_type: edge_case
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/dehabthexorcist/configs/Dehabthexorcist_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/dehabthexorcist/configs/Dehabthexorcist_interaction_config.yaml
    generation_ratio: 0.25
  config_3:
    config:
      min_u: 0
      max_u: 1000000
      min_v: 0
      max_v: 1000000
      case_type: medium
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/dehabthexorcist/configs/Dehabthexorcist_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/dehabthexorcist/configs/Dehabthexorcist_interaction_config.yaml
    generation_ratio: 0.25
  config_4:
    config:
      min_u: 0
      max_u: 1000000000000000000
      min_v: 0
      max_v: 1000000000000000000
      case_type: random
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/dehabthexorcist/configs/Dehabthexorcist_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/dehabthexorcist/configs/Dehabthexorcist_interaction_config.yaml
    generation_ratio: 0.25

# 全局配置
global_config:
  # 指令生成器类的完整路径
  class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.dehabthexorcist.Dehabthexorcist_instruction_generator.DehabthexorcistInstructionGenerator"
  
  # 随机种子配置
  enable_random_seed: true
  default_seed: 999
  
  # 数据集划分配置
  default_split_samples:
    train: 1000
    test: 100
  
  # 是否启用数据打乱
  shuffle: true

  # 是否生成parquet文件
  gen_parquet: false
