instruction_generators:
  config_1:
    config:
      n_range: [1, 10000]
      m_range_low: 2
      m_range_high: 500
      g_range: [1, 500]
      r_range: [1, 500]
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/enastyaandunexpectedguest/configs/Enastyaandunexpectedguest_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/enastyaandunexpectedguest/configs/Enastyaandunexpectedguest_interaction_config.yaml
    generation_ratio: 0.25
  config_2:
    config:
      n_range: [1, 500]
      m_range_low: 2
      m_range_high: 200
      g_range: [1, 200]
      r_range: [1, 200]
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/enastyaandunexpectedguest/configs/Enastyaandunexpectedguest_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/enastyaandunexpectedguest/configs/Enastyaandunexpectedguest_interaction_config.yaml
    generation_ratio: 0.25
  config_3:
    config:
      n_range: [1, 1000]
      m_range_low: 2
      m_range_high: 300
      g_range: [1, 300]
      r_range: [1, 300]
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/enastyaandunexpectedguest/configs/Enastyaandunexpectedguest_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/enastyaandunexpectedguest/configs/Enastyaandunexpectedguest_interaction_config.yaml
    generation_ratio: 0.25
  config_4:
    config:
      n_range: [1, 100]
      m_range_low: 2
      m_range_high: 100
      g_range: [1, 100]
      r_range: [1, 100]
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/enastyaandunexpectedguest/configs/Enastyaandunexpectedguest_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/enastyaandunexpectedguest/configs/Enastyaandunexpectedguest_interaction_config.yaml
    generation_ratio: 0.25

# 全局配置
global_config:
  # 指令生成器类的完整路径
  class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.enastyaandunexpectedguest.Enastyaandunexpectedguest_instruction_generator.EnastyaandunexpectedguestInstructionGenerator"
  
  # 随机种子配置
  enable_random_seed: true
  default_seed: 999
  
  # 数据集划分配置
  default_split_samples:
    train: 1000
    test: 100
  
  # 是否启用数据打乱
  shuffle: true

  # 是否生成parquet文件
  gen_parquet: false
