interaction:
  - name: "Ethegreatmixing_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.ethegreatmixing.Ethegreatmixing_interaction.EthegreatmixingInteraction"
    config: {}
