interaction:
  - name: "Feuclidsnightmare_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.feuclidsnightmare.Feuclidsnightmare_interaction.FeuclidsnightmareInteraction"
    config: {}
