interaction:
  - name: "Dkuroandgcdandxorandsum_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.dkuroandgcdandxorandsum.Dkuroandgcdandxorandsum_interaction.DkuroandgcdandxorandsumInteraction"
    config: {}
