interaction:
  - name: "Candryushaandcoloredballoons_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.graphical_puzzles.candryushaandcoloredballoons.Candryushaandcoloredballoons_interaction.CandryushaandcoloredballoonsInteraction"
    config: {}
