interaction:
  - name: "Edoubleprofiles_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.graphical_puzzles.edoubleprofiles.Edoubleprofiles_interaction.EdoubleprofilesInteraction"
    config: {}
