interaction:
  - name: "Cremoveadjacent_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.cremoveadjacent.Cremoveadjacent_interaction.CremoveadjacentInteraction"
    config: {}
