interaction:
  - name: "Bweirdjourney_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.bweirdjourney.Bweirdjourney_interaction.BweirdjourneyInteraction"
    config: {}
