interaction:
  - name: "Cluckypermutation_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.cluckypermutation.Cluckypermutation_interaction.CluckypermutationInteraction"
    config: {}
