interaction:
  - name: "BBEHHyperbaton_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.language_analysis.bbehhyperbaton.BBEHHyperbaton_interaction.BbehhyperbatonInteraction"
    config: {}
