interaction:
  - name: "Celectriccharges_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.mathematical_modeling.celectriccharges.Celectriccharges_interaction.CelectricchargesInteraction"
    config: {}
