instruction_generators:
  config_1:
    config:
      max_n: 5000
      max_p: 50000
      max_t: 500000
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cqueueinthetrain/configs/Cqueueinthetrain_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cqueueinthetrain/configs/Cqueueinthetrain_interaction_config.yaml
    generation_ratio: 0.17
  config_2:
    config:
      max_n: 10000
      max_p: 1000000
      max_t: 1000000
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cqueueinthetrain/configs/Cqueueinthetrain_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cqueueinthetrain/configs/Cqueueinthetrain_interaction_config.yaml
    generation_ratio: 0.17
  config_3:
    config:
      max_n: 50000
      max_p: 500000
      max_t: 500000
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cqueueinthetrain/configs/Cqueueinthetrain_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cqueueinthetrain/configs/Cqueueinthetrain_interaction_config.yaml
    generation_ratio: 0.17
  config_4:
    config:
      max_n: 100000
      max_p: 1000000000
      max_t: 1000000000
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cqueueinthetrain/configs/Cqueueinthetrain_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cqueueinthetrain/configs/Cqueueinthetrain_interaction_config.yaml
    generation_ratio: 0.17
  config_5:
    config:
      max_n: 100
      max_p: 1000
      max_t: 1000
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cqueueinthetrain/configs/Cqueueinthetrain_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cqueueinthetrain/configs/Cqueueinthetrain_interaction_config.yaml
    generation_ratio: 0.17
  config_6:
    config:
      max_n: 1000
      max_p: 10000
      max_t: 100000
    tool_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cqueueinthetrain/configs/Cqueueinthetrain_tool_config.yaml
    interaction_config_path: internbootcamp/bootcamps/bootcamps_v1/algorithm/cqueueinthetrain/configs/Cqueueinthetrain_interaction_config.yaml
    generation_ratio: 0.17

# 全局配置
global_config:
  # 指令生成器类的完整路径
  class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.cqueueinthetrain.Cqueueinthetrain_instruction_generator.CqueueinthetrainInstructionGenerator"
  
  # 随机种子配置
  enable_random_seed: true
  default_seed: 999
  
  # 数据集划分配置
  default_split_samples:
    train: 1000
    test: 100
  
  # 是否启用数据打乱
  shuffle: true

  # 是否生成parquet文件
  gen_parquet: false
