interaction:
  - name: "E2chiorianddollpickinghardversion_interaction"
    class_name: "internbootcamp.bootcamps.bootcamps_v1.algorithm.e2chiorianddollpickinghardversion.E2chiorianddollpickinghardversion_interaction.E2chiorianddollpickinghardversionInteraction"
    config: {}
